on:
  push:
    branches: [main]

name: Build SuSo training site

jobs:
  build-suso-site:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          # use version on dev machine
          r-version: '4.4.1'
          use-public-rspm: true

      # TODO: add this once site works with regular GHA
      # - name: Set up renv
      #   uses: r-lib/actions/setup-renv@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.57

      - name: Install R packages need to build site
        uses: r-lib/actions/setup-r-dependencies@v2
          with:
            # Quarto installed in setp above
            install-quarto: false
            # install packages with pak and all required system dependencies
            packages: |
              glue
              htmltools
              here
              gt
              purrr
              tibble
              fs
              dplyr
              knitr
              fontawesome
              emoji
              quarto

      - name: Remove development .gitignore and create deployment one
        run: |
          rm .gitignore
          echo "/.quarto/" >> .gitignore

      - name: Build site
        run: quarto::quarto_render()
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          clean: true
          folder: docs
          branch: gh-pages
          target-folder: docs
